### ISSUE TITLE
Erroneous results?

### ISSUE THREAD

**Issue by ivan-marroquin** [robince/gcmi#5]
Hi,

I am using Python 3.6.5 on a windows machine. I generate 2D data sets: linear and nonlinear distributions, following the Python code at https://minepy.readthedocs.io/en/latest/python.html

By the way, these distributions are shown in the paper "A statistical framework for neuroimaging data analysis based on mutual information estimated via a gaussian copula"

Then, I created my script to compute GCMI and got these results:
a) 7 linear distributions: 
26.4952
0.7085
0.1584
0.0015
0.1033
0.7295
10.5505

I would expect that the first and last to have a GCMI of 1 - assuming 1 is the highest value meaning a perfect dependence

b) 7 nonlinear distributions:
-0.0004
-0.0001
-0.0003
-0.0003
0.0004
0.0022
-0.0003

What is the meaning of negative correlation values? why are these values so low?

I attached to this issue: my script and input data.

Many thanks,

Ivan

[Python_GCMI_2D_Synthetic_Data.zip](https://github.com/robince/gcmi/files/3135239/Python_GCMI_2D_Synthetic_Data.zip)

**Comment by robince** [comment]
> I would expect that the first and last to have a GCMI of 1 - assuming 1 is the highest value meaning a perfect dependence

This is not really how MI works - it gives units of bits which is bounded by the minimum of the two entropies (in the discrete case). In the continuous case it is unbounded. In the discrete case various normalisations are possible to get a value bounded by 1, but I'm not sure how that can be done in the continuous case (see e.g. Figure 3 Ince et al. HBM).

> What is the meaning of negative correlation values? why are these values so low?

GCMI is approximate MI estimator which gives a lower bound to the true MI under the assumption of a Gaussian copula dependence. I think it is likely in those non-linear datasets GCMI lower bound is not tight, e.g. GCMI is not sensitive to those sorts of non-linear effects. In the paper I used binned methods there to make that point in the general introduction to MI. In general you can think of GCMI as sensitive to similar effects as rank correlation (in 1d vs 1d case), but obviously with the extension to multivariate and discrete variables, and multivariate quantities (like conditional mutual information). 

The negative values are likely due to bias correction. Because MI is a non-negative quantity any non-negative estimator will have a positive bias - ie positive mean value over multiple realisations when there is no dependence. Bias correction removes this mean, with the idea that after correction the expected value of the sample estimate from samples where there is no dependence should be zero. Effectively GCMI is estimating a value of zero for all of those non-linear examples and the small positive or negative values are sampling noise in the (unbiased) estimator.  

If you need sensitivity to such non-linear effects you should use a different estimator - options I am aware of include binning the continuous data and using binned estimates, kernel density methods, or methods based on nearest neighbours (Kraskov methods).

**Comment by ivan-marroquin** [comment]
Many thanks for the clarification
